package model;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "CART")
public class Cart extends IdAutoGeneratedEntity{

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart", cascade = CascadeType.ALL)
    private Set<Items> items = new HashSet<>();

    private String customerName;

    public Cart() {
    }

    public Cart(Set<Items> items, String customerName) {
        this.items = items;
        this.customerName = customerName;
    }

    public Set<Items> getItems() {
        return items;
    }

    public void setItems(Set<Items> items) {
        this.items = items;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @Override
    public String toString() {
        return "Cart2{" +
                "items=" + items +
                ", customerName='" + customerName + '\'' +
                '}';
    }
}
