package model;

import javax.persistence.*;
import java.util.*;

@Entity
@Table(name = "CartTable")
public class Cart extends IdAutoGeneratedEntity{

    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Items> items = new ArrayList<>();

    private String customerName;

    public Cart() {
    }

    public Cart(List<Items> items, String customerName) {
        this.items = items;
        this.customerName = customerName;
    }

    public List<Items> getItems() {
        return items;
    }

    public void setItems(List<Items> items) {
        this.items = items;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    @Override
    public String toString() {
        return "Cart2{" +
                "items=" + items +
                ", customerName='" + customerName + '\'' +
                '}';
    }
}
